### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by normanu** [wamdam/backy2#1]
What packages are needed to make the package?

- virtualenv
- python3-dev
- python3-pexpect

But I still am unable to make the package.

[code]
pex.resolver.Untranslateable: Package SourcePackage('file:///root/backy2/build/.pex/psycopg2-2.6.2.tar.gz') is not translateable by ChainedTranslator(EggTranslator, SourceTranslator)
Makefile:27: recipe for target 'build/backy2.pex' failed
make: *** [build/backy2.pex] Error 1
[/code]

**Comment by wamdam** [comment]
Hi, sorry - I just realized this bug is here.
make deb
should do all the work.
Depending on the database you want to use, you might want to install python3-<yourdatabase> after installing the deb, because only the sqlalchemy dependency is listed.

For more details look at the [debian](https://github.com/wamdam/backy2/tree/master/debian) directory.

**Comment by schannall** [comment]
Maybe you should also add this to the README.md

Regards, Jonas

**Comment by wamdam** [comment]
Added enhancement #2
