### ISSUE TITLE
Scrubbing needs to be performed per backup version

### ISSUE THREAD

**Issue by olifre** [wamdam/backy2#20]
In a common setup, Backy2 is used to backup snapshots of RBD volumes which are used by KVM machines. In this way, most backup versions will share the very same blocks. 

Issuing a scrub for each single Backy2 backup version will scrub the very same blocks many times to my understanding (e.g. if I keep 20 snapshots, and some parts of the system did no change in the last 20 days). Partial scrubbing helps, but does not fully solve the issue. 

I'd propose to implement a scrubbing mechanism which allows to scrub all chunks known to the full set of backup versions, which could be used alternatively to scrubbing each single version.

**Comment by elemental-lf** [comment]
You're correct, the object on the backend storage will be checked (i.e. downloaded in the case of S3) repeatedly. One idea would be to introduce some kind of bulk scrubbing which could scrub multiple versions at once and then keep track which backend objects have been scrubbed already. A Bloomfilter might be useful here, so that the tracking database doesn't get out of hand memorywise for large backup sets. Another idea would be to go with the bulk scrubbing approach but to remove the duplicates before the scrubbing starts.
Incidentally I've been working on a fork of Backy2 which already includes such a bulk scrubbing function (see https://benji-backup.me/scrub.html#bulk-scrubbing). I think your suggestion could be integrated quite easily and I'll probably just do it at some point in the future. I'm currently building the Ceph cluster where Benji will be used, I'm going to revisit Benji after that.

**Comment by elemental-lf** [comment]
l needed to move fast and it took some time to get in touch with Daniel. In the meantime Daniel and I had a longer phone call about Backy2 and he's okay with the fork. But this is getting off-topic. We can continue this discussion via email (see my profile) if you want. If it relates directly to a bug or feature in Benji or something similar you can also open an issue at the usual place. Thanks!

**Comment by wamdam** [comment]
Quite old one, github didn't bother to inform me about issues it seems.
Interesting idea and I think it's worth implementing. But it's not exactly our usecase as we have to handle bandwidth here. We're currently doing 15% deep scrub with source per day always on the latest version, so we have a pretty good statistical chance of hitting a backup error if there is some within one week.
