### ISSUE TITLE
Empty diff list causes a full backup

### ISSUE THREAD

**Issue by wamdam** [wamdam/backy2#3]
When the rbd diff returns an empty list [] backy reads the full volume.

**Comment by david-caro** [comment]
This seems to keep happening, will try to add more info, but as of right now, we are doing a backup of an rbd image, and when the hints are empty, it seems to do a full backup anyhow.

Maybe I'm doing something wrong (looking), any hints are appreciated. Will update here with the findings.

ps. thanks for backy2!

**Comment by david-caro** [comment]
Update on this, the reads work ok, as they are skipped, but it seems that any block that was not in the hints will anyhow get it's metadata written.

I might be mistaken, but I would not expect the metadata to get updated either, let me know if that's expected.

 I'll keep looking in the meantime.

**Comment by wamdam** [comment]
metadata is always fully written. This is expected and a design choice.

**Comment by david-caro** [comment]
Thanks for the reply!
I see, interesting, I'm guessing that the rationale is that even though the data did not change, there's still some change on the metadata?

It seems to be copying the exact same metadata for the new block though, that's why I ask (I might be missing something): https://github.com/wamdam/backy2/blob/master/src/backy2/backy.py#L749 and https://github.com/wamdam/backy2/blob/master/src/backy2/backy.py#L794

**Comment by david-caro** [comment]
I tried skipping the metadata and ended up with a backup with just 1 block xd, I guess that there's a bit more logic somewhere else when writing the metadata that adds the backup version <-> metadata link (got extremely fast backups though! hahaha).
