### ISSUE TITLE
deb packet dependency not correct

### ISSUE THREAD

**Issue by ednt** [wamdam/backy2#49]
Hi,

to backup disks from an older ProxMox CEPH cluster I installed the deb package.
This ProxMox is based an debian jessie.
I noticed that I need python3-sqlalchemy >= 1.1.11
Ok, so I installed python3-pip and downloaded this by hand.
But still no luck. An error at backy2 initdb occured in sql.py line 178.
After some investigations I found the 'bug':

alembic_cfg.attributes['connection'] = connection

attributes is available since 0.7.5
https://alembic.sqlalchemy.org/en/latest/api/config.html

In debian jessie 0.6.5 is installed.

After installing 0.7.6 with
pip3 install alembic==0.7.6

And copy the files to the correct directory backy2 worked without problems.

The dependencies in the deb packet should be extended to reflect this:
python3-alembic (>= 0.7.5)

It could save some time :)

**Comment by wamdam** [comment]
Actually I have just downgraded the requirement to sqlalchemy>=1.0.11 in order to be compatible with ubuntu 16.04 (again) in the code. It just wasn't pushed (which it is now).
Actually - at least on ubuntu - I try to be compatible with default system libraries. It shouldn't ideally be necessary to pip install. As I don't have a debian machine, could you try the current state and install the deb? I'd be interested on what should be changed.

**Comment by ednt** [comment]
Hi,

debian jessie (8.xx)
alembic 0.6.5
sqlalchemy 0.9.8

debian stretch (9.xx)
alembic 0.8.8
sqlalchemy 1.0.15

So it is no problem to use your dep package in debian stretch.
But for jessie you should add the additional dependency for alembic (>=0.7.5)
Then an experienced user can see what he have to do to make it run.

**Comment by wamdam** [comment]
Alright, you mean just like this?
https://github.com/wamdam/backy2/commit/fc6c8f3e4e078553ce2f694cd4e58683b44d0234
Does this help?

**Comment by ednt** [comment]
yes, the resulting warning will give a good hint to bring it up on 'older' systems.

Danke!
