### ISSUE TITLE
How about to support RBD images within some namespace.

### ISSUE THREAD

**Issue by jpsn123** [wamdam/backy2#89]
ceph `rbd.py` is old version, can you update it?, thanks. 
let be external depends may be a good idea.

**Comment by wamdam** [comment]
This is as you recommend it since Apr. 5th 2020:
https://github.com/wamdam/backy2/commit/fc5bba5f7551a18f6502e379d8143c0b7c4ba7d0#diff-cfbda1effbdbd5ef6e773521c0176f771e422e4520b9c4e484e7d4fe88e8335f

The local copy of the rbd lib is only used when there's no other one installed, plus it outputs a warning.
Doesn't this work for you?
